-- Query Sharing Infrastructure Schema
-- Version: 27
-- Description: Add tables for query sharing, collaboration, and team knowledge sharing

-- Shared Queries
CREATE TABLE {table_prefix}CB_SHARED_QUERIES (
    QUERY_ID            CHAR(36) PRIMARY KEY,
    QUERY_NAME          VARCHAR(255) NOT NULL,
    DESCRIPTION         VARCHAR(2000),
    SQL_QUERY           TEXT NOT NULL,
    CONNECTION_ID       VARCHAR(255),
    SCHEMA_NAME         VARCHAR(255),
    CREATED_BY          VARCHAR(128) NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VISIBILITY          VARCHAR(50) DEFAULT 'PRIVATE' NOT NULL,
    TEAM_ID             VARCHAR(128),
    IS_TEMPLATE         CHAR(1) DEFAULT 'N' NOT NULL,
    TAGS                TEXT,
    METADATA            TEXT,
    
    FOREIGN KEY (CREATED_BY) REFERENCES {table_prefix}CB_AUTH_SUBJECT(SUBJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (TEAM_ID) REFERENCES {table_prefix}CB_AUTH_SUBJECT(SUBJECT_ID) ON DELETE SET NULL
);

-- Query Permissions
CREATE TABLE {table_prefix}CB_QUERY_PERMISSIONS (
    PERMISSION_ID       CHAR(36) PRIMARY KEY,
    QUERY_ID            CHAR(36) NOT NULL,
    USER_ID             VARCHAR(128),
    TEAM_ID             VARCHAR(128),
    PERMISSION          VARCHAR(50) NOT NULL,
    GRANTED_BY          VARCHAR(128) NOT NULL,
    GRANTED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY (QUERY_ID) REFERENCES {table_prefix}CB_SHARED_QUERIES(QUERY_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES {table_prefix}CB_AUTH_SUBJECT(SUBJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (TEAM_ID) REFERENCES {table_prefix}CB_AUTH_SUBJECT(SUBJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (GRANTED_BY) REFERENCES {table_prefix}CB_AUTH_SUBJECT(SUBJECT_ID) ON DELETE CASCADE
);

-- Query Comments
CREATE TABLE {table_prefix}CB_QUERY_COMMENTS (
    COMMENT_ID          CHAR(36) PRIMARY KEY,
    QUERY_ID            CHAR(36) NOT NULL,
    USER_ID             VARCHAR(128) NOT NULL,
    COMMENT_TEXT        VARCHAR(4000) NOT NULL,
    PARENT_ID           CHAR(36),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    IS_DELETED          CHAR(1) DEFAULT 'N' NOT NULL,
    
    FOREIGN KEY (QUERY_ID) REFERENCES {table_prefix}CB_SHARED_QUERIES(QUERY_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES {table_prefix}CB_AUTH_SUBJECT(SUBJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_ID) REFERENCES {table_prefix}CB_QUERY_COMMENTS(COMMENT_ID) ON DELETE CASCADE
);

-- Query Versions (for history tracking)
CREATE TABLE {table_prefix}CB_QUERY_VERSIONS (
    VERSION_ID          CHAR(36) PRIMARY KEY,
    QUERY_ID            CHAR(36) NOT NULL,
    VERSION_NUMBER      INTEGER NOT NULL,
    SQL_QUERY           TEXT NOT NULL,
    CHANGED_BY          VARCHAR(128) NOT NULL,
    CHANGE_DESCRIPTION  VARCHAR(1000),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY (QUERY_ID) REFERENCES {table_prefix}CB_SHARED_QUERIES(QUERY_ID) ON DELETE CASCADE,
    FOREIGN KEY (CHANGED_BY) REFERENCES {table_prefix}CB_AUTH_SUBJECT(SUBJECT_ID) ON DELETE CASCADE,
    UNIQUE (QUERY_ID, VERSION_NUMBER)
);

-- Query Favorites (user-specific)
CREATE TABLE {table_prefix}CB_QUERY_FAVORITES (
    FAVORITE_ID         CHAR(36) PRIMARY KEY,
    QUERY_ID            CHAR(36) NOT NULL,
    USER_ID             VARCHAR(128) NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY (QUERY_ID) REFERENCES {table_prefix}CB_SHARED_QUERIES(QUERY_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES {table_prefix}CB_AUTH_SUBJECT(SUBJECT_ID) ON DELETE CASCADE,
    UNIQUE (QUERY_ID, USER_ID)
);

-- Query Executions (analytics)
CREATE TABLE {table_prefix}CB_QUERY_EXECUTIONS (
    EXECUTION_ID        CHAR(36) PRIMARY KEY,
    QUERY_ID            CHAR(36) NOT NULL,
    USER_ID             VARCHAR(128) NOT NULL,
    EXECUTION_TIME_MS   BIGINT,
    ROW_COUNT           INTEGER,
    STATUS              VARCHAR(50) NOT NULL,
    ERROR_MESSAGE       VARCHAR(2000),
    EXECUTED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY (QUERY_ID) REFERENCES {table_prefix}CB_SHARED_QUERIES(QUERY_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES {table_prefix}CB_AUTH_SUBJECT(SUBJECT_ID) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX {table_prefix}IDX_SHARED_QUERIES_CREATED_BY ON {table_prefix}CB_SHARED_QUERIES(CREATED_BY);
CREATE INDEX {table_prefix}IDX_SHARED_QUERIES_TEAM ON {table_prefix}CB_SHARED_QUERIES(TEAM_ID);
CREATE INDEX {table_prefix}IDX_SHARED_QUERIES_VISIBILITY ON {table_prefix}CB_SHARED_QUERIES(VISIBILITY);
CREATE INDEX {table_prefix}IDX_SHARED_QUERIES_CREATED_AT ON {table_prefix}CB_SHARED_QUERIES(CREATED_AT);

CREATE INDEX {table_prefix}IDX_QUERY_PERMISSIONS_QUERY ON {table_prefix}CB_QUERY_PERMISSIONS(QUERY_ID);
CREATE INDEX {table_prefix}IDX_QUERY_PERMISSIONS_USER ON {table_prefix}CB_QUERY_PERMISSIONS(USER_ID);
CREATE INDEX {table_prefix}IDX_QUERY_PERMISSIONS_TEAM ON {table_prefix}CB_QUERY_PERMISSIONS(TEAM_ID);

CREATE INDEX {table_prefix}IDX_QUERY_COMMENTS_QUERY ON {table_prefix}CB_QUERY_COMMENTS(QUERY_ID);
CREATE INDEX {table_prefix}IDX_QUERY_COMMENTS_USER ON {table_prefix}CB_QUERY_COMMENTS(USER_ID);
CREATE INDEX {table_prefix}IDX_QUERY_COMMENTS_PARENT ON {table_prefix}CB_QUERY_COMMENTS(PARENT_ID);

CREATE INDEX {table_prefix}IDX_QUERY_VERSIONS_QUERY ON {table_prefix}CB_QUERY_VERSIONS(QUERY_ID);
CREATE INDEX {table_prefix}IDX_QUERY_VERSIONS_VERSION ON {table_prefix}CB_QUERY_VERSIONS(QUERY_ID, VERSION_NUMBER);

CREATE INDEX {table_prefix}IDX_QUERY_FAVORITES_QUERY ON {table_prefix}CB_QUERY_FAVORITES(QUERY_ID);
CREATE INDEX {table_prefix}IDX_QUERY_FAVORITES_USER ON {table_prefix}CB_QUERY_FAVORITES(USER_ID);

CREATE INDEX {table_prefix}IDX_QUERY_EXECUTIONS_QUERY ON {table_prefix}CB_QUERY_EXECUTIONS(QUERY_ID);
CREATE INDEX {table_prefix}IDX_QUERY_EXECUTIONS_USER ON {table_prefix}CB_QUERY_EXECUTIONS(USER_ID);
CREATE INDEX {table_prefix}IDX_QUERY_EXECUTIONS_TIME ON {table_prefix}CB_QUERY_EXECUTIONS(EXECUTED_AT);
